using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MJ.Models.WrathAndGlory
{
    public class CompetencesService
    {
        public List<Competence> GetListeCompetences()
        {
            List<Competence> ListeCompetences = new List<Competence>();

            ListeCompetences.Add(new Competence(1, "Athlétisme", "Cette compétences représene votre capacité à courir, sauter et nager en fonction de votre force physique.\nLa difficulté d'un test est déterminée par ce que vous espérez faire ainsi que par votre environement.\nVous pouvez utiliser cette compétences pour effectuer une Attaque Déstabilisante afin de mettre votre adversaire en position désavantagueuse."));
            ListeCompetences.Add(new Competence(2, "Capacité de Combat", "Cette compétence représente votre habilité au combat rapproché, que ce soit avec une arme ou à mains nues. Cela comprend l'identification, la connaissance et l'entretien des armes de mêlée.\nSi vous essayer de toucher quelqu'un, la Défense de votre cible détermine le SD de votre test. La complexité et la rareté d'une arme de mêlée détermine le SD pour la préparation, l'identfication et l'entretien d'une arme."));
            ListeCompetences.Add(new Competence(3, "Capacité de Tir", "Cette compétence représente votre habilieté à utiliser les armes à feu et autre armes à distance. Cela comprend l'identification, la connaissance et l'entretien de ces armes.\nSi votre personnage tir sur quelqu'un, la Défense de sa sible détermine le SD du test. La compexité de la rareté d'une arme à distance peuvent détermir le SD pour la réparer, l'identifier et l'entretien de cette arme."));
            ListeCompetences.Add(new Competence(4, "Commandement", "Cette compétence représente votre capacité à convaincre les autres à se mettre en danger. Vous pouvez utiliser cette compétence pour inspirer le respect et pousser vos camarades au-delà de leur limites.\nLa difficuleté d'un test dépend de qui vous essayer de diriger et des ordre que vous essayer de donner. Des soldats fidèles et expérimentés de l'Astra Militarum sont plus faciles à commander que des habitants des bas-fonds non entraînés, et il est plus facile de convaincre quelqu'un d'aider à éteindre l'incendie de sa maison que de rejoindre une charge contre une ordre d'Orks.\nLe commandement peut être utilisé pour rallier vos camarades et annuler les conditions Effrayé, Terrorisé et Pilloné."));
            ListeCompetences.Add(new Competence(5, "Connaissance", "Cette compétence représente votre capacité à vous rappeler des savoirs appris lors de vos études. Une compétence de Connaissance élevée signifie que vous avez passé du temps à étudier de nombreux sujet et que vous pouvez facilement vous souvenir de ce que vous avez appris. Cette compétence couvre à la fois les informations vitales et obscures, les annonces publiques et les connaissances interdites: tout ce que votre personnage à pu apprendre.\nLa difficuleté d'un test est déterminée par le degré de complexité des savoirs auxquels vous essayer d'accéder.\nIl n'est pas necessaire de faire un test pour tout ce que votre personnage devrait savoir facilement, comme des informatinos sur votre planète natale ou des connaissances de base sur votre Faction. Si vous faites un test sur quelque chose en rapport avec un Mot-Clé, ajouter +1 par Mot-Clé associé."));
            ListeCompetences.Add(new Competence(6, "Duperie", "Cette compétence représsente votre capacité à mentir de manière convaincante.\nQu'il s'agisse d'un mensonge pour et simple, d'une formulation trompeuse ou d'une flatterie peu sincère, plus vous onbtenez un résultat élevé sur votre test, plus votre cible est susceptible de vous croire.\nLes mensonges les plus flagrants ont des SD plus élevés. Si vous faites un test de Duperie, potentiel test opposé avec un test de Psychologie. Si vous réussissez, votre interlocuteur vous croire, mais dans le cas contraire, il saura que vous mentez.\nVous pouvez utiliser Duperie pour faire une Attaque Déstabilisante, afin d'inciter l'adversaire à commettre une erreur et à se mettre en position de faiblesse."));
            ListeCompetences.Add(new Competence(7, "Furtivité", "Cette compétence représente votre capacité à vous cacher, à vous déplacer sans être détécté et à désactivé des systèmes de sécurité.\nLorsque vous essayer de vous déplacer sans être détecté autour de PNJ, le résultat de votre test est compaté à leur vigilance passive. Si des PNJ vous recherchent et que vous essayer de rester caché, le résulstat de votre test est en opposition à leur test de Vigilance. La situation dans laquelle vous vous trouvez, en partculier l'éclairage et le bruit ambiant, peut donner des bonus ou des malus à un test.\nLa difficuleté d'un test pour contourner un système de sécurité dépend de l'éfficacité de ce dernier: un simple cadenas mécanique est beaucoup plus simple à déjouer que les dispositifs de sécurité d'un Croiseur Imperial."));
            ListeCompetences.Add(new Competence(8, "Intimidation", "Cette compétence représente votre capacité à effrayer les gens pour qu'il fassent, que ce soit par la force, la contrainte ou les menaces.\nLa difficulté d'un test dépend de la personne que vous essayer d'Intimider. Si vous avez plus d'armes et une meilleure position sociale, elle sera plus facile à convaincre. Cependant, si la cible est également bien armée et très respectée, la difficulté du test sera plus élevée. Posibilité d'utiliser l'Intimidation d'un PNJ pour définir le SD.\nVous pouvez utiliser cette compétence pour effectuer une Attaque Destabilisante, afin d'effrayer votre adversaire pour le faire reculer."));
            ListeCompetences.Add(new Competence(9, "Investigation", "Cette compétence représente votre capacité à déchiffrer des indices, effectuer des recherche et à rassembler des informations via les canaux appropriés.\nVous pouvez utliiser cette compétence pour trouvez une informationspécifique dans une archive impériale, ou pour juger lequel des objets que vous avez trouvés sur une scène de crime est particullièrement pertinent pour l'affaire que vous essayer de résoudre.\nLa difficulté d'un test est basée sur la complexité et les informations disponibles.\nSouvent, vous pourrez rassembler des indices sans faire de test. Les tests sont utilisés orsque votre personnage peut réellemnt voir les informations et, en tant que tel, peut utiliser ses propre capacités pour déchiffrer un indice, ou quand votre personnage doit faire des recherches importantes."));
            ListeCompetences.Add(new Competence(10, "Maîtrise Psychique", "Cette compétences représente votre capacité à manifester des pouvoirs psychiques et à manipuler le Warp pour changer la réalité.\nVous ne pouvez pas acheter cette compétence à moins d'avoir le mot-clé PSYKER."));
            ListeCompetences.Add(new Competence(11, "Medicae", "Cette compétence représente votre capacité à diagnostiquer et à guérir. Cette compétence peut être utilisée pour identifier les maladies les toxines et contrer leurs effets, ainsi que pour remédier à d'autres maux en utilisant les premiers soins ou la chirurgie.\nLa difficuleté du test dépend du problème que vous essayer de corriger ou de la rareté de ce que vous tentez d'identifier. Un os cassé serait facile à identifier, alors qu'une maladie rare aurait un SD élevée pour être diagnotiquée.\nGVous pouvez également utiliser une Action de Combat pour effectuer un test afin d'accomplir l'un des effets ci-dessous. Si vous tentez d'utiliser cette compétence sur vous-même, le test est effectué avec un malus de +1 SD d'un minimum de 1, avec des pénalités plus élevées pour les espèces plus différentes de la vôtre.\nSoigner des blessures\nRetirer une condition\nRestaurer du Stress."));
            ListeCompetences.Add(new Competence(12, "Persuasionh", "Cette compétence représente votre capacité à conva  incre les autres et à changer leur opinions. Grâce à la logique, à des plaidoyers passionnés ou des vives négociations, vous pouvez influer l'attitude d'un individu à votre égard ou affecter les actions qu'il envisage d'entreprendre. Cette commpétence est nottement utilisée pour essayer de convaincre quelqu'un de vous aider.\nLa difficulté pour les test est basée sur l'opinion actuelle de la cible sur vous et sur ce que vous lui demandez de faire.Si la cible n'est pas amicale envers vous ou votre Faction, oiu si vous l'avez déçue par le passé, le test sera plus difficile. Si vous lui demandez de faire quelque chose qui nécessite de faire un sacrifice ou de se mettre en danger, il sera plus difficile de la persuader.\nVous pouvez utiliser cette compétence pour lancer une Attaque Déstabilisante, afin de perturber votre cible avec des mots mielleux et de propos ambigus."));
            ListeCompetences.Add(new Competence(13, "Pilotage", "Cette compétence représente votre capacité à contrôler un véhicule.\nChaque fois que vous conduisez un céhiccule sur terre, sur mer, dans les airs ou dans l'espace, vous utiliser cette compétence. Si vous avez une formation dans cette compétence, vous n'aurez pas à faire de test pour vous rendre d'un endroit à un autre. Cepandant, si vous essayer de faire des manoeuvres audacieuses ou de conduire dans des circonstances dangereuses, vous devrez faire un test pour continuer à avancer à grande vitesse ou pour éviter de vous écraser.\nLa difficuleté du test dépend des circonstances environnementales, de votre familiarité avec le véhicule, de l'état de ce dernier et de la complexité de ce que vous essayer de faire. Si un véhicule vous est inconnu ou bien s'il est endommagé, vous avez plus de difficullé à le piloter, notamment par mauvais teps ou lorsque vous essayer d'effectuer une manoeuvre delicate."));
            ListeCompetences.Add(new Competence(14, "Psychologie", "Cette compétence représent votre capacité à capter les signaux sociaux des autres pour discerner leurs motivations.\nVous pouvez effectuer un test lorsque vous soupçonnez que quelqu'un ment ou pour déteceter quelque chose d'étrange dans son comportement. Cela peut être plus difficile dans le cadre d'interactions sociale avec des individus d'autres cultures, mais des personnages particulièrement perspicaces peuvent toujours déterminer si quelqu'un ment ou dit la vérité.\nLa difficulté d'un test est soit défini en fonction de la capacité du personnage à cacher ses intentions, soit via un test opposé contre la Duperie du personnage."));
            ListeCompetences.Add(new Competence(15, "Ruse", "Cette compétence représente votre capacité à penser et à agir comme ceux qui agissent en dehors de la loi.\nVous pouvez faire un test pour écouter les rumeurs du moment, pour trouver des revendeurs de marchandises ou d'informations illicites ou pour élaborer un plan insidieux. Chaque fois que vous réussissez un test, vous parvenez à accomplir quelque chose d'astucieux sans attirer d'attention indésirable.\nLa difficuleté des test pour trouver ders personnes ou des objets est déterminée par la difficuleté à les localiser. Les objets rares, exotiques et illégaux nécessient des SD plus élevés pour être trouvés, tout comme les personnes capables de se déplacer discrètementet de couvrir leurs traces.\nSi vous essayer de marcher avec quelqu'un ou de l'exposer pendant l'interrogatoire, les PJ peut demander un test opposé. Si vous cherchez un moyen sournois de résoudre un problème, le MJ peut demander un test avec un SD basé sur le stress que vous subissez actuellement."));
            ListeCompetences.Add(new Competence(16, "Survie", "Cettec ompétence représente votre capacité à trouver des provisions, à sécuriser un abri et à pister ou naviguer dans un environnement naturel. Si vous voulez chercher de la onurriture, vous mettre à l'abri de la civilisation, trouver un chemin à travers la nature sauvage ou suivre des traces de pas jusqu'à leur source, vous devrez faire un test.\nLa difficulté d'un test est basée sur l'environnement. Trouver de la nourriture est facile sur un agri-monde, difficile sur un monde hostile et impossible sur un monde stérille sans atmosphère."));
            ListeCompetences.Add(new Competence(17, "Technomaîtrise", "Cette compétence représente votre capacité à comprendre, utiliser, réparer et démanteler la technologie.\nLa difficulté d'un test est déterminée par la complexité de la technologie avec laquelle vous interagissez et la précision de la tâche que vous essayer d'effectuer. Les SD du tableau correspondent à des interactions avec des appareils technologique de votre espèce propres à votre espèce; tenter un test sur la technologie d'une autre espèce pourrait augmenter le SD."));
            ListeCompetences.Add(new Competence(18, "Vigilance", "Cette compétence représente votre capacité à observer des détails et des altérations de l'environnement, ainsi qu'à trouver des choses cachées.\nLa difficulté des tests est déterminée par la difficulté à remarquer quelque chose. Si vous essayer de repérer une personne qui se cache, le SD du test est basé sur son score de Furtivité."));
            ListeCompetences.Add(new Competence(98, "Passive", "Correspond à la Vigilance Passive d'un personnage"));
            ListeCompetences.Add(new Competence(99, "Par Défaut", "Correspond à toutes les compétences non nomées."));

            return ListeCompetences;
        }
    }
}