using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MJ.Models.WrathAndGlory
{
    public class TalentService
    {
        public List<Talent> GetListTalent()
        {
            List<Talent> ListeTalent = new List<Talent>();

            ListeTalent.Add(new Talent(1, "[Attribut] Surhumain(e)", "60", "Score d'[Attribut] 5+", "Lorsque vous prenez ce Talent, vous devez sélectionner l'un de vos Attributs avec un score de 5 ou plus. Ce Talent s'applique à cet Attribut.\nChaque fois que vous effectuez un test avec l'Attribut choisi, vous gagnez + Double de votre Rang dés bonus."));
            ListeTalent.Add(new Talent(2, "[Compétence] Surnaturel(e)", "60" , "Score de [Compétence] 4+", "Choisissez n'importe quelle Compétence avec un score de 4+.\nLorsque vous effectuez un test avec la Compétence sélectionné, réduisez tous les modificatures SD du Double de votre Rang, jusqu'à un minimum de 0. Cela n'affecte pas la difficulté de base de la tâche, seulement les éventuels modificateurs. Ils peut par exemple s'agir de faiure un test sans les outils appropriés, dans l'obscurité totale, ou bien une option de combat spécifique."));
            ListeTalent.Add(new Talent(3, "[Trait] Amélioré(e)", "40" , "", "Augmentez un de ces Traits de + Rang:\n- Conviction\n- Défense\n- Résistance\n- Résolution\n- Stress\n- Détermination\n- Vitesse\n- Blessures"));
            ListeTalent.Add(new Talent(4, "Ange de la mort", "30" , "Rang 2 +, Espèce Adeptus Astartes", "Vous êtes un Space Marine, un des guerriers les plus redoutés de la galaxie. Vous êtes un soldat surhumain et surentraîné, le vétéran de plusieurs centaines de batailles et un maître du maniement de nombreuses armes mortelles.\nAjouter + Rang à la valeur totale des dégâts des attaques réussies avec les armes suivantes:\n- Épées tronçonneuses\n- Haches tronçonneuses\n- Épées énergétiques\n- Gantelets énergétiques\n- Attaques à mains nues\n- Armes à Bolt\n- Toutes les armes avec le mot-clé Adeptus Astartes\n\nA la discrétion du MJ, ce Talent peut également s'appliquer aux armes avec le mot-clé CHAOS pours les Sapce Marines du Chaos."));
            ListeTalent.Add(new Talent(5, "Arme de prédilection", "30" , "", "Vous vous êtes entraîné intensivement avec une seule arme que vous gardez toujours sur vous. Elle est presque devenue une extension de votre corps.\nChoisissez une de vos armes comme arme de prédilection. Ce Talent n'affecte que cette arme et acune autre de son type.\nChauqe fois que vous réussissez une attaque avec cotre arme de prédilection, vous infligez + Double de votre Rang DS.\nSi vous perdez ou détruisez votre arme de prédilection, vous ne pouvez plus recevoir d'avantages de ce Talent. Collaborez avec le MJ pour déterminer si un remplacement approprié peut être trouvé; cela pourrait être l'objet de toute votre aventure."));
            ListeTalent.Add(new Talent(6, "Attaque écrasante", "20" , "Score de Capacité de Combat 2+", "Vous pouvez concentrez toute votre force et votre rage en une seule attaque; cette frappe est mortelle, mais elle vous laisse à découvert.\nVous gagnez + Rang DS lors de n'importe quelle Attaque à outrance."));
            ListeTalent.Add(new Talent(7, "Augmentique", "20 + le nombre de PX égal à la valeur de l'Augmentique que vous choisissez" , "", "Vous remplacez une partie de votre organisme par un Augmentique, le nom commun des implants cybernétiques dasn l'Imperium.\nVous pouvez prendre plusieurs fois ce Talent. Chaque fois que vous prenez ce Talent, vous pouvez sélectionner deux Augmentiques de rareté Rare ou inférieure, ou un seul Augmentique Très Rare.\nLe MJ détermine quels Augmentiques sont disponibles (généralement ceux conçu pour votre epsèce) et qui peut effectuer la procédure d'installation nécessaire."));
            ListeTalent.Add(new Talent(8, "Berzerk", "20" , "", "La seule vue du sang suffit à provoquer chez vous une rage noire.\nChaque fois que vous voyez un individu à moins de 30m de vous subir un Coup Critique ou la Condition Saignement, vous gagnez 1 point de Fureur. Le MJ peut vous demaner de faire un test de Corruption SD 1 chaque fois que ce Talent est activé."));
            ListeTalent.Add(new Talent(9, "Bombardement", "40" , "Rang 2 +, un des Mots-Clés suivants:\n- Adeptus Astartes\n- Aeldari\n- Astra Militarum\n- Chaos\n- Ork\n- Togue Trader", "Vous disposez des contacts et du soutien militaire requis pour lancer une frappe aérienne. Ce bombardement peut provenir d'artillerie au sol, d'aéronefs ou même d'un vaisseau en orbite basse. Dans tous les cas, les attaques sont dévastatrices pour leur cibles.\nUne fois par session de jeu, un personnage avec ce Talent et doté de moyens de communication avec son vaisseau ou d'autres forces armées peut demander un bonbardement. L'attaque de bonbardement inflige 20 dégâts + Double de votre Rang DS à toutes les cibles à moins de Rang x 10m de la cible désignée."));
            ListeTalent.Add(new Talent(10, "Brute", "20" , "Score de Force 3 +", "Vos attaques portent des coups brutaux, quelle que soit l'arme utilisée.\nChaque arme de mêlée que vous utliisez possède le Trait d'arme Brutal, y compris pour vos attaques à mains nues.\nSi vous réussissez une attaque de m^lée avec une arme qui possède déjà le Trait d'arme Brutal, vous infligez + 1 dégât supplémentaire. Ce bonus de dégât est appliqué après le calcul de vos défâts totaux, il ne s'ajoute pas à l avaleur de dégâts de l'arme."));
            ListeTalent.Add(new Talent(11, "Charge furieuse", "20" , "Score d'Athlétisme 2 + et score de Capacité de Comabt 2 +", "Vous vous êtes entraîné à vous rapprocher rapidement d'un ennemi. Frapper en courant ne vous pose aucun problème.\nVous gagneé + Rang dés bonus pour toute attaque de mêlée que vous effectuez dans e cadre d'une Charge."));
            ListeTalent.Add(new Talent(12, "Combat à deux armes", "20" , "", "Vous pouvez maniez une arme dans chaque mains, la pénalité au SD pour l'utilisation de l'option Attaques multiples est réduite de 2. Chaque arme doit avoir le Trait Pistolet ou être une arme de mêlée à une main.\nVous pouvez également utiliser une arme différente pour chacune de vos Attaque multiples, en faisant des jets de dégâts séparés pour chauqe arme."));
            ListeTalent.Add(new Talent(13, "Combat aveugle", "20" , "Vigilance 3 +", "vous vous êtes entraîné à combattre à l'aveugle, en vous fiant à votre instinct et à d'autres sens pour détecter et éliminer vos ennemis même lorsque vous ne pouvez pas voir.\nLa Condition Aveuglé n'affecte pas vos test d'attaque utilisant vote Capacité de combat."));
            ListeTalent.Add(new Talent(14, "Concentration multiple", "20" , "Score de Maîtrise psychique 4 +", "Vous avez pratiqué l'art de divisé vos pensées, ce qui vous permet de vous concentrer plus efficacement sur la manipulation du Warp de deux manières à la fois.\nLa pénalité de SD due au maintien de plusieurs Pouvoirs psychiques est réduite de 2."));
            ListeTalent.Add(new Talent(15, "Contre-attaque", "30" , "Score de Capacité de Combat 5 +", "Maître du combats au corps à corps, vous parvenez toujours à trouver une ouverture dans la garde de votre adversaire lorsqu'il attaque.\nVous pouvez utiliser ce Talent chaque fois qu'un ennemeis vous cible avec une attaque de mêlée. Une fois que l'ennemi a terminé son attaque, vous pouvez effectuer une seule attaque de mêlée contre lui. Ceci est traité comme votr'e Action de réaction, mais vous pouvez Contre-attaquer jusqu'à Rang x par Round.\nVousne pouvez pas appliquer d'autres Talent, Aptitudes ou options de combats à une Contre-attaque.\nSi vous Contre-attaquer, vous ne pouvez pas effectuer d'Action de déplacement lors de votre prochain tour."));
            ListeTalent.Add(new Talent(16, "Conversation calculée", "10" , "Mot-clé Adeptus Mechanicus", "Les dispositifs de cogitation qui forment votre cerveau sont ajustés avec précision. Grâce à la froide pureté de la logique, vous pouvez calculer les résultats probables d'une conversation et prédire les réponses des esprits biologiques plus limité que le vôtre.\nAvant de faire un test de Compétence Ruse, Duperie, Psychologie ou Persuasion, vous pouvez choisir d'activer ce Talent pour utiliser cotre Compétence Technomaîtrise à la place.\nVous devez effectuer un Tassemblement ou un Repos avant de pouvoir utiliser à nouveau ce Talent."));
            ListeTalent.Add(new Talent(17, "Coup bas", "20" , "", "Vous maîtrisez l'art du combat déloyal. Chaque fois que vous effectuez une Attauqe déstabilisante et que vous Convertissez 2 Icône exaltées, vous pouvez infliger à votre cible une Condition supplementaire. Choisissez la Condition la plus appropriée du point de vue narratif parmi les options suivantes:\n- A terre\n- Aveuglé\n- Entravé\n- Secoué"));
            ListeTalent.Add(new Talent(18, "Déduction", "20" , "Score d'Intelligence 3 +", "Votre esprit studieux peut facilement démêler un problème (ou une personne).\nEn tant qu'Action simple, vous pouvez utliser ce Talent pour faire un test de Compétence basé sur l'Intelligence pour vous rappeler ou remarquer quelque chose à propos d'une cible. La cible peut être n'importe quoi, d'une porte à verrouillage magnétique avec un esprit de machine acariâtre à un gouverneur planétaire impénétrable.\nSi vous réussissez le test, le MJ peut vous donner des informations basées sur la Compétence que vous avez utilisée pour faire le test. Vous gagnez également + Rang dés bonus pour tout test effectué contre cette cible en utilisant cette information. Vous pouvez donner ce bonus à un allié si vous lui communiquez ce que vous avez appris."));
            ListeTalent.Add(new Talent(19, "Dévots", "30" , "Score de Commandement 4 +", "Grâce à votre réputation ou à votre mission, vous avez rassemblé un certain nombre d'adeptes qui feront tout ce que vous demandez. Si vous êtes attaqué, ils interviennent.\nVos fidèles sont une Horde de n'importe quelle Menace de niveau Troupe. Un nombre de fidèle égale au Double de votre Rang + 2 a décidé de vous suivre. Pour chaque dévos utiliser les règles suivantes:\n- Les Attributs des dévots sont égaux à 1 + Double de votre Rang.\n- Les Compétences des dévots sont égales à 1 + Double de votre Rang\n- Les Attributs et les Compétences des dévots ne peuvent pas être supérieurs aux vôtres.\n\nChaque fois que vous êtes touché par une attaque, un de vos fidèles peut effectuer un test d'Initiative SD 5 en tant qu'Action de réaction. En cas de succès, l'attaque tue le dévot au lieu de vous toucher.\nLes fidèles tués peuvent être remplacés gratuitement la prochaine fois que vous visiterez un campement ou une ville importante.\nSi vous prenez ce Talent plusieurs fois, vous gagnez plus de fidèles du même type que vous possédez déjà. Si vous avez déjà des adeptes dû à une Aptitude d'Archétype, ce Talent fournit à la place des adeptes supplémentaires de ce type."));
            ListeTalent.Add(new Talent(20, "Dur à cuire", "20" , "", "Vous êtes difficile à tuer. Lorsque vous subissez plus de Blessure que votre Maximum de blessures, vous n'êtes pas Mourant. Faites un jet sur le Tableau des Blessures de guerre et soignez 1 Blessure.\nVous ne pouvez plus réutiliser ce Talent jusqu'à votre prochain Rassemblement."));
            ListeTalent.Add(new Talent(21, "Éliminateur", "20" , "Score de furtivité 2 +", "Vous frappez dans l'ombre et utilisez l'élément de surprise pour tuer vos ennemis en un coup.\nLorsque vous possédez un Score de Furtivité et que vous attaquez un ennemi qui ne vous a pas remarqué, vous pouvez ajouter votre Score de Furtivité comme DS, en plus des bonus liés à une Attaque surprise. Toute diminution de votre Score de Furtivité est résolue après l'attaque."));
            ListeTalent.Add(new Talent(22, "Élu du Warp", "40" , "Mot-clé Psyker", "Le Warp est aussi dangereux que capricieux, et ses horreures affectent certains malheureux plus que d'autres. Même les Psykers qui font preuve d'un puissant conditionnement mental et semble maîtriser leurs pouvoirs psychiques ne sont pas à l'abri de l'instabilité du Warp.\nVous pouvez utiliser ce Talent pour relancer n'importe quel jet sur la table Périls du Warp. Vous devez accepter le nouveau résultat."));
            ListeTalent.Add(new Talent(23, "Endurci", "30" , "Score d'Endurence 3 +", "Vous bénéficiez d'une grande résistance naturelle, ou bien vous avez suivi un entraînement d'endurence éprouvant.\nEn tant qu'Action de combat, vous pouvez effectuer un test d'Endurence SD 3. En cas d'échec, vous récupérez 1 Stress. En cas de succès, Vous récupérez 1 + Double de votre Rang en Stress. Chaque Icône exaltée Copnvertie permet également de récupérer un point de Stress supplémentaire.\nUne fois que vous avez utilisé ce Talent, vous ne poouvez plus l'utiliser tant que vous n'avez pas terminer un Rassemblement."));
            ListeTalent.Add(new Talent(24, "Esprit du Warp", "30" , "Score de Maîtrise Psychique 4 +", "Vous avez ouvert votre esprit pour accéder à un autre Domaine psychique, soit par une discipline et une étude intenses, soit par une exposition traumatisante au Warp.\nVous pouvez apprendre des Pouvoirs psychiques d'un Domaine psychique supplémentaire.\nVous pouvez choisir de prendre de la Corruption pour réduire le coût en PX de ce Talent. Pour chaque point de Corruption que vous prenez, réduisez le coût en PX de 5."));

            return ListeTalent;
        }
    }
}