using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MJ.Models.WrathAndGlory
{
    public class TraitArmeService
    {
        public List<TraitArme> ListTraitsArmes()
        {
            List<TraitArme> ListTraitArme = new List<TraitArme>();
                
            ListTraitArme.Add(new TraitArme(1, "Assaut", "Ces armes sont pensées pour tirer tout en se précipitant droit vers l'ennemi.\nVous pouvez tirer avec une arme d'Assaut dans le cadre d'un Sprint, mais le test d'attaque reçoit alors une pénalité de + 2 SD."));
            ListTraitArme.Add(new TraitArme(2, "Brutal", "Les armes avec ce Trait infligent des blessures effroyables. Quand vous lancez des dés de dégâts supplémentaires pour une arme Brutale:\n- Les résultats de 1 et 2 infligent 0 dégât.\n- Les résultats de 3 et 4 infligent 1 dégât.\n- Les résultats de 5 et 6 infligent 2 dégâts."));
            ListTraitArme.Add(new TraitArme(3, "Dispersion", "Ces armes à gros calibre font des ravages parmi les combattants serrés les uns contre les autres.\nQuand elle est utilisée à Courte Portée, une arme à Dispersion peut toucher n'importe quel nombre de cibles tant qu'elles se trouvent toutes à moins de 3 mètres les unes des autres. Lorsque vous tirez avec une telle arme sur une Horde, vous gagnez + 3 dés bonus."));
            ListTraitArme.Add(new TraitArme(4, "Douloureux", "Conçues pour infliger un maximum de douleur, ces armes affectent autant l'esprit et le moral que le corps.\nChaque Blessure infligé par une arme possédant ce Trait inflige également 1 point de Stress."));
            ListTraitArme.Add(new TraitArme(5, "Électro", 1, "La décharge électrique mortelle des armes Électro pertube les systèmes électroniques des céhicules.\nLes armes Électro gagnent + DS égal à leur score lorsque vous les utilisez pour attaquer un véhicule."));
            ListTraitArme.Add(new TraitArme(6, "Encombrant", 1, "Qu'elles soient déséquilibrées ou trop grosses, certainses armes sont difficiles à utiliser.\nLe SD des attaques effectuées avec des armes dotées de ce Trait est augmenté d'un montant égale au score de ce Trait."));
            ListTraitArme.Add(new TraitArme(7, "Explosion", 1, "Les armes explosives peuvent frapper plusieurs ennemis en une seule attaque.\nLorsque vous tirez avec ou lancez une arme à Explosion, choisissez n'importe quel point à portée (y compris un autre personnage), puis effectuez un test de Capacité de Tir SD 3. Les effets de Portée sont appliqués normalement, sauf si vous utilisez une arme de lancer comme une grenade. Si vous échouez au test, l'attaque rate et se Disperse. Si vous réussissez l'explosion est centrée sur votre cible.\nSi vous mesurez la distance, le Score d'Explosion détermine le rayon en mètres de la déflagration. Toute personne à l'intérieur de ce rayon est touchée par l'attaque.\nSi vous cibler une Horde ou que vous utilisez une méthode \"Théâtre de l'esprit\" simpllifiée, le nombre d'individus à proximité touchés par l'explosion est égal à la moitié du Score d'Explosion.\nVous ne pouvez pas Convertir pour augmenter les dégâts d'une arme à Explosion. Si vous infligez un Coup Critique avec une arme à Explosion, les effets  s'appliquent à toutes les cibles touchées par l'attaque."));
            ListTraitArme.Add(new TraitArme(8, "Fiable", "Ces armes sont robustes et facile à entretenir.\nVous pouvez ignorer la première Complication liée à cette arme dans une scène. Les tests effectués pour réparer ou entretenir les armes Fiables sont effectués avec + 1 dé bonus."));
            ListTraitArme.Add(new TraitArme(9, "Flamme", 1, "Les armes dotées de ce Trait crachent un jet de liquide chimique brûlant. Ce torrent de flammes peut être guidé par le porteur d'une telle arme pour enflammer plusieurs ennemis.\nLes attaques effectuées avec une arme à Flamme ignorent la couverture. Si vous touchez une cible avec cet Équipement, un liquide enflammé remplit l'espace entre vous et votre cible en ligne droite. Tout ce qui se trouve dans cette zone est également touché par l'attaque.\nVous pouvez Convertir lorsque vous effetuez un Test d'attaque à distance avec une arme à Flamme pour incliner le flux de produits chimiques enflammés sur un nombre de mètres égal à votre Score de Capacité de Tir. Tout ce qui se trouve dans cette zone est touché par l'attaque.\nChaque fois que vous touchez plusieurs cibles, faites un seul jet de dégâts et appliquez ces derniers à toutes les cibles. N'importe quelle cible peut tenter de réduire les dégâts.\nUne arme avec ce Trait est considérée comme possédant le Trait Inflige (En Feu)."));
            ListTraitArme.Add(new TraitArme(10, "Force", "Les Psykers peuvent canaliser la puissance du Warp à travers les circuits éthériques et les matériaux psychoréactifs de ces armes.\nSi vous avez le Mot-Clé Psyker, vous pouvez ajouter la moitié de votre Score de Force Mentale à la valeur de dégâts d'une arme de Force. Si vous n'avez pas le Mot-CLé Psyker, les dégâts d'une arme de Force sont diminué de 2."));
            ListTraitArme.Add(new TraitArme(11, "Fusion", "Les rafales subatomiques qui jaillissent de ces armes font fondre la chair et réduisent l'armure en scories.\nLorsque vous lancez des dés de dégâts supplémentaires pour une arme à Fusion tirée à Courte Portée:\n- Les résultats de 1 et 2 infligent 0 dégât.\n- Les résultats de 3 et 4 infligent 1 dégâts\n- Les résultats de 5 et 6 infligent 2 dégâts.\nLorsque vous lancez desd dés de dégâts supplémentaires pour une arme à Fusion tirée contre un véhicule ou une fortification à Courte Portée:\n-Les résultats de 1, 2 et 3 infligent 1 dégât.\n-Les résultats de 4, 5 et 6 dégâts."));
            ListTraitArme.Add(new TraitArme(12, "Inflige", 1, "", "Ces armes sont conçues pour nuire à la cible de manière cruelle et inhabituelle.\nChaque arme dotée de ce Trait applique une Condition particulière à sa cible si elle provoque une Blessure.\nSi une arme avec Inflige possède un nombre, celui-ci détermine le Seuil de difficulté de n'importe quel test effectué pour supprimé la Condition."));
            ListTraitArme.Add(new TraitArme(13, "Kustom", "Quand vous faites l'acquisition d'une arme avec ce Trait, ce dernier peut être remplacé par n'importe quel autre Trait d'arme de votre choix.Si le Trait que vous sélectionnez à un Score , lancez 1d3 pour déterminer sa valeur."));
            ListTraitArme.Add(new TraitArme(14, "Lourd", 1, "Les armes grandes et encombrantes sont difficiles à manier avec précision.\nVous devez avoir une Force égale au score du Trait de l'arme pour utiliser celle-ci normalement. Toutes les attaques avec une atme dotée de ce Trait sont effectuées avec une pénalité de + 2 SD si vous ne posséfez pas la Force minimale. Si vous obtenez une Complication dans le cadre d'une attaque avec une telle arme, vous êtes projeté A Terre en plus de tout autre effet.\nL'action Caler ou l'installation d'une arme avec ce Trait sur un trépied ou un dispositif similaire permettent d'annuler ce Trait."));
            ListTraitArme.Add(new TraitArme(15, "Parade", "Vous pouvez utiliser ces armes pour dévier les coups.\nVous gagnez + 1 Défense contre les attaques de mêlée lorsque vous maniez une arme dotée de ce Trait"));
            ListTraitArme.Add(new TraitArme(16, "Perforant", 1, "Ces armes puissantes traversent aisément les armures.\nQuand vous convertissezune Icône éxaltée dans le cadre d'une attaque avec une arme dotée de ce Trait, la PA de l'arme est améliorée par le Score de Perforant pour cette attaques."));
            ListTraitArme.Add(new TraitArme(17, "Pistolet", "Ces armes sont pensées pour être légères, afin de pouvoir être dégainées rapidement et uéilisées en combat rapproché.\nLes Pistolets peuvent être utilisés en étant Engagé."));
            ListTraitArme.Add(new TraitArme(18, "Précis", 1, "Ces armes sont optimisées pour être très précises à Longue Portée.\nLorsque vous Viséz avec une arme dotée de ce Trait, vous gagnez + 1 dé bonus à l'attaque et + DS égal au Score du Trait."));
            ListTraitArme.Add(new TraitArme(19, "Radiation", 1, "Les substances radioactives dangereuses tirées par ces armes corrodent irrévocablement la chair.\nLorsque vous lancez des dés de dégâts supplémentaires pour une arme à Radiation, vous ajoutez le Score de ce Trait aux résultats de dés."));
            ListTraitArme.Add(new TraitArme(20, "Silencieux", "Ces armes furtives sont conçues pour infliger des dégâts aussi discrètement que possible.\nLorsqu'une arme avec ce Trait est utilisée dans le cadre d'une attaque, vote Score de Furtivité n'est réduit que de 2."));
            ListTraitArme.Add(new TraitArme(21, "Surcharge", "Les armes à plasma peuvent être surchargées avent de cracher la matière surchauffées qui leur sert de munition. Grâce à cette méthode, ces armes sont particulièrement dangereuses pour leur cible, mais leur utilisatuer peut aussi en subir les conséquences.\nVous pouvez choisir de tirer avec une arme dotée de ce Trait en mode Surcharge. Si vous obtenez une Complication, vous subissez 1d6 Blessures mortelles. Si vous touchez, l'arme inflige + 3 DS supplémentaires."));
            ListTraitArme.Add(new TraitArme(22, "Tir Rapide", 1, "Ces armes sont capables de faire pleuvoir rapidement la mort à courte portée.\nSi vous tirez avec une arme à Tire Rapide à Courte Portée, vous gagnez des dés de dégâts supplémentaires égaux au Score de ce Trait."));
            ListTraitArme.Add(new TraitArme(23, "Waaagh!", "Les armes des Orks défient l'entendement. Elles violent toutes les lois de la mécanique et de la physique, mais grâce au pouvoir des croyances des peaux-vertes, elles n'en sont que plus mortelles.\nSi vous êtes uun Ork, vous gagnez + 1 dé bonus aux attaques avec une arme dotée de ce Trait. Si vous êtes également Blessé, vous infligez + 1 DS supplémentaire."));
            ListTraitArme.Add(new TraitArme(24, "Warp", "Qu'elles soient alimentées par l'énergie psychique, pas des xenotechnologies ou par la puissance brute du Chaos, rares sont ceux qui peuvent faire face à ces armes impies et en sortir indemnes.\nUne arme Warp possède une valeur de dégâts égale à la Résistance totale - 4 de la cible, à moins que les dégâts indiqués dans le profil de l'arme ne soient plus élevées."));

            return ListTraitArme;
        }
    }
}